# Generated by Django 3.2.8 on 2021-10-29 16:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20211029_1653'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrictype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 29, 16, 53, 15, 936528)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tailoringstyle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 29, 16, 53, 19, 768850)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tailoringstyle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_customer_own_fabric', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('total_meters', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Meters')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity')),
                ('deliver_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_branch', to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
                ('fb_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbrc_typ', to='orders.fabrictype')),
                ('tailr_styl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tailr_styl', to='orders.tailoringstyle')),
            ],
            options={
                'verbose_name': 'Order Book',
                'verbose_name_plural': 'Order Book',
                'ordering': ['-id'],
            },
        ),
    ]
