# Generated by Django 3.2.8 on 2021-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='pocket',
            field=models.CharField(blank=True, choices=[('P1', 'Pocket1'), ('P2', 'Pocket2'), ('P3', 'Pocket3'), ('P4', 'Pocket4')], default='P1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='zip',
            field=models.CharField(blank=True, choices=[('Z1', 'Zip1'), ('Z2', 'Zip2'), ('Z3', 'Zip3'), ('Z4', 'Zip4')], default='Z1', max_length=2, null=True),
        ),
    ]
