# Generated by Django 3.2.8 on 2021-11-13 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_address'),
        ('orders', '0002_auto_20211106_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orders',
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='deliver_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 8, 52, 35, 926543)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='is_customer_own_fabric',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalorders',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='orders',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_branch', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliver_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 8, 52, 45, 117750)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_customer_own_fabric',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='collar',
            field=models.CharField(choices=[('C1', 'Collar1'), ('C2', 'Collar2'), ('C3', 'Collar3'), ('C4', 'Collar4'), ('P1', 'Pocket1'), ('P2', 'Pocket2'), ('P3', 'Pocket3'), ('P4', 'Pocket4'), ('Z1', 'Zip1'), ('Z2', 'Zip2'), ('Z3', 'Zip3'), ('Z4', 'Zip4')], default='C1', max_length=2),
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
