# Generated by Django 3.2.8 on 2021-10-29 21:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211029_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount for One Order')),
                ('country', django_countries.fields.CountryField(default='KW', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailr_styl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tailr_styl_payment', to='orders.tailoringstyle')),
            ],
            options={
                'verbose_name': 'Pricing plans',
                'verbose_name_plural': 'Pricing plans',
                'ordering': ['-id'],
            },
        ),
    ]
