# Generated by Django 3.2.8 on 2021-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='penpocket',
            field=models.CharField(choices=[('PP1', 'PenPocket1'), ('PP2', 'PenPocket2'), ('PP3', 'PenPocket3'), ('PP4', 'PenPocket4'), ('PP5', 'PenPocket5'), ('PP6', 'PenPocket6')], default='PP1', max_length=5),
        ),
        migrations.AddField(
            model_name='measurements',
            name='pocket',
            field=models.CharField(choices=[('P1', 'Pocket1'), ('P2', 'Pocket2'), ('P3', 'Pocket3'), ('P4', 'Pocket4')], default='P1', max_length=2),
        ),
        migrations.AddField(
            model_name='measurements',
            name='pockettwo',
            field=models.CharField(choices=[('P21', 'PocketTwo1'), ('P22', 'PocketTwo2'), ('P23', 'PocketTwo3'), ('P24', 'PocketTwo4'), ('P25', 'PocketTwo5'), ('P26', 'PocketTwo6')], default='P21', max_length=5),
        ),
        migrations.AddField(
            model_name='measurements',
            name='tie',
            field=models.CharField(choices=[('T1', 'Tie1'), ('T2', 'Tie2'), ('T3', 'Tie3'), ('T4', 'Tie4'), ('T5', 'Tie5'), ('T6', 'Tie6'), ('T7', 'Tie7'), ('T8', 'Tie8'), ('T9', 'Tie9')], default='T1', max_length=5),
        ),
    ]
