# Generated by Django 3.2.8 on 2021-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211029_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='handSize',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hand Size'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='insidePocket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inside Pocket'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='mainWidth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Width'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='penPocket_select',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pen Pocket'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='sholderOne',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shoulder One'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='sholderTwo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shoulder Two'),
        ),
    ]
