# Generated by Django 3.2.8 on 2021-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211030_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='button',
            field=models.CharField(choices=[('BTN1', 'Button1'), ('BTN2', 'Button2')], default='BTN1', max_length=5),
        ),
        migrations.AddField(
            model_name='measurements',
            name='cufflink',
            field=models.CharField(choices=[('CL1', 'Cufflink1'), ('CL2', 'Cufflink2'), ('CL3', 'Cufflink3'), ('CL4', 'Cufflink4'), ('CL5', 'Cufflink5'), ('CL6', 'Cufflink6'), ('CL7', 'Cufflink7'), ('CL8', 'Cufflink8')], default='CL1', max_length=5),
        ),
        migrations.AddField(
            model_name='measurements',
            name='insidepocketshape',
            field=models.CharField(choices=[('IPS1', 'InsidePocketShape1'), ('IPS2', 'InsidePocketShape2')], default='IPS1', max_length=5),
        ),
    ]
