# Generated by Django 3.2.8 on 2021-10-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20211030_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amnt_to_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Total Amount to Pay')),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Amount Paid')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Balance Amount')),
                ('order_status', models.CharField(choices=[('OS1', 'Ordered'), ('OS2', 'COMPLETED'), ('OS3', 'DELIVERED')], default='OS1', max_length=5)),
                ('payment_status', models.CharField(choices=[('PS1', 'NOT PAID'), ('PS2', 'PARTIALLY PAID'), ('PS3', 'FULLY PAID')], default='PS1', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_order_customer', to=settings.AUTH_USER_MODEL)),
                ('measurements', models.ManyToManyField(to='orders.Measurements')),
                ('orders', models.ManyToManyField(to='orders.OrderBook')),
            ],
            options={
                'verbose_name': 'Complete Order',
                'verbose_name_plural': 'Complete Order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrders',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('total_amnt_to_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Total Amount to Pay')),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Amount Paid')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Balance Amount')),
                ('order_status', models.CharField(choices=[('OS1', 'Ordered'), ('OS2', 'COMPLETED'), ('OS3', 'DELIVERED')], default='OS1', max_length=5)),
                ('payment_status', models.CharField(choices=[('PS1', 'NOT PAID'), ('PS2', 'PARTIALLY PAID'), ('PS3', 'FULLY PAID')], default='PS1', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Complete Order',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
