# Generated by Django 3.2.8 on 2021-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_historicalorders_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Single Order Amount'),
            preserve_default=False,
        ),
    ]
