# Generated by Django 3.2.8 on 2021-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_pricingplans_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorders',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Balance Amount'),
        ),
        migrations.AlterField(
            model_name='historicalorders',
            name='total_amnt_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Total Amount to Pay'),
        ),
        migrations.AlterField(
            model_name='historicalorders',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount Paid'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Balance Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amnt_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Total Amount to Pay'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount Paid'),
        ),
        migrations.AlterField(
            model_name='pricingplans',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Single Order Amount'),
        ),
    ]
