# Generated by Django 3.2.8 on 2021-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20211030_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurements',
            options={'ordering': ['-created_at'], 'verbose_name': 'Measurements', 'verbose_name_plural': 'Measurement'},
        ),
        migrations.AlterModelOptions(
            name='orderbook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Book', 'verbose_name_plural': 'Order Book'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complete Order', 'verbose_name_plural': 'Complete Order'},
        ),
        migrations.AlterField(
            model_name='historicalorders',
            name='total_amnt_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount to Pay'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amnt_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount to Pay'),
        ),
    ]
