# Generated by Django 3.2.8 on 2021-10-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20211030_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID')),
                ('total_amnt_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount to Pay')),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Amount Paid')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Balance Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('order_status', models.CharField(choices=[('OS1', 'Ordered'), ('OS2', 'COMPLETED'), ('OS3', 'DELIVERED')], default='OS1', max_length=5)),
                ('payment_status', models.CharField(choices=[('PS1', 'NOT PAID'), ('PS2', 'PARTIALLY PAID'), ('PS3', 'FULLY PAID')], default='PS1', max_length=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orders.orders')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
