# Generated by Django 3.2.8 on 2021-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_delete_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorders',
            name='payment_method',
            field=models.CharField(choices=[('PM1', 'CASH'), ('PM2', 'CREDIT CARD'), ('PM3', 'DEBIT CARD'), ('PM4', 'PAY LATER')], default='PM1', max_length=5),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('PM1', 'CASH'), ('PM2', 'CREDIT CARD'), ('PM3', 'DEBIT CARD'), ('PM4', 'PAY LATER')], default='PM1', max_length=5),
        ),
    ]
