# Generated by Django 3.2.8 on 2021-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colors',
                'verbose_name_plural': 'Colors',
                'ordering': ['-id'],
            },
        ),
    ]
